title: Welcome all Ye Great and Small :smirk:
author: Kerry
email:  5903381+raven123crow@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome folks to my webpage for my github-pages-with-jekyll repo!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
